### ISSUE TITLE
Does icon of the addon appear somewhere on the firefox toolbar?

### ISSUE THREAD

**Issue by iG8R** [WeaselStorm/ChannelPointCollector#5]
**Describe the bug**
After installation there is no addon's icon on the firefox toolbar.

**To Reproduce**
1. Install addon
2. No icon of the addon on the firefox toolbar

**Expected behavior**
To see some icon on the toolbar with any information concerning the job made by addon.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Firefox 95.0.2 64-bit

**Comment by RDP8** [comment]
> **Describe the bug** After installation there is no addon's icon on the firefox toolbar.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Install addon
> 
>     2. No icon of the addon on the firefox toolbar
> 
> 
> **Expected behavior** To see some icon on the toolbar with any information concerning the job made by addon.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Windows 10 64-bit
> 
>     * Firefox 95.0.2 64-bit

Same.

**Comment by WeaselStorm** [comment]
The standard for addons is that you only have the icon if there are settings or information to show. As there are no settings or anything, the icon does not show there. If you want to toggle the collector on or off, currently the only option is to disable/enable the addon in the `about:addons` page.
